---
on: # yamllint disable-line rule:truthy
  merge_group:
  push:
    branches:
      - master
      - develop
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - 'pnpm*'
      - '.github/**'
      - 'tsconfig.json'
      - 'tsconfig.node.json'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - 'pnpm*'
      - '.github/**'
      - 'tsconfig.json'
      - 'tsconfig.node.json'

name: 🔍 Continuous integration

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        node: ['20']

    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: ♻️ Restore packages cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: ${{ runner.os }}-packages-cache-${{ hashFiles('**/pnpm*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-packages-cache-${{ hashFiles('**/pnpm*.yaml') }}

      # Lint packages that have changed (--include & --since)
      - name: 🚨 Linter
        run: |
          pnpm --filter "...[origin/master]" run lint
